# Generated by Django 5.2.6 on 2025-09-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_saleitem_quantity_alter_saleitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('transfer', 'Bank Transfer'), ('digital', 'Digital Wallet')], default='cash', max_length=20),
        ),
    ]
